### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by HIMix** [Mykybo/PUBG-Radar#2]
Hi @Mykybo,

Could you provide requirements to set this to work at clearly fresh VM? Trying to set this up at Google Cloud Compute Engine.

Will be cool if it will be provided as list of commands, such as:
sudo apt-get install dsniff
...

And maybe advice what type of linux it's better to use here (Debian/Ubuntu/etc.)

Thanks a lot!

**Comment by HIMix** [comment]
Also I just get to "routing step" (arp.sh)... and... is it possible to set this thing up if my gaming PC is not at the same local network as PC where I want this PUBG-Radar to be (I'm trying to set it on Google Cloud VM)?

**Comment by Mykybo** [comment]
Remote vm is gonna be a problem because arp spoofing works only in LAN. You would have to setup some kind of tunnel (such as OpenVPN), but the problem is that this cheat cannot read such packets. There is implemented a basic PPTP protocol (replace PortFilter with PPTPFilter in the run script) but I haven't tested it.

**Comment by HIMix** [comment]
@Mykybo thanks for an answer. My thoughts was the same and you confirmed'em. Sad but true :)

**Comment by Dragonflyss** [comment]
Radar is not working anymore
